Repository WISDEM/LandBOSSE, pull requests merged in 2020-05, with the labels that each got.

#140 Issue 137
  landbosse/landbosse_api/run.py
Labels: enhancement

#128 Issue 117 Merge private CollectionCost into public CollectionCost module
  landbosse/model/CollectionCost.py
  landbosse/tests/model/test_CollectionCost.py
Labels: approved

#134 Issue 125 Merge private SitePreparationCost into public SitePreparationCost module
  landbosse/excelio/XlsxReader.py
  landbosse/model/SitePreparationCost.py
  landbosse/tests/model/test_SitePreparationCost.py
Labels: approved

#122 Issue 111 integrate dw erection: Merge private (LandBOSSE-dev) ErectionCost module into public ErectionCost module
  project_input_template/README.md
Labels: ready

#143 Merge private repository of landbosse into public repo
  .travis.yml
  landbosse/excelio/XlsxReader.py
  landbosse/model/CollectionCost.py
  landbosse/model/CostModule.py
  landbosse/model/FoundationCost.py
  landbosse/model/GridConnectionCost.py
  landbosse/model/ManagementCost.py
  landbosse/model/SitePreparationCost.py
  landbosse/model/SubstationCost.py
  landbosse/tests/model/test_CollectionCost.py
  landbosse/tests/model/test_FoundationCost.py
  landbosse/tests/model/test_GridConnectionCost.py
  landbosse/tests/model/test_SitePreparationCost.py
  landbosse/tests/model/test_SubstationCost.py
  project_input_template/README.md
  project_input_template/project_list.xlsx
  project_input_template/project_list_utility.xlsx
Labels: ready
